<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<p>ini halaman admin</p>
	<li><a href="#nav1">navigation 1</li></a>
	<li><a href="#nav2">navigation 2</li></a>
	<li><a href="#nav3">navigation 3</li></a>

	<div id="nav1">
		<section>
			<p>  untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project.  untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeignit<br>er kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect d<br>i codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project.</p>

		</section>
	</div>

	<div id="nav2">
		<section>
			<p>  untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project.  untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library <br>untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter <br>itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project.</p>
		</section>
	</div>

	<div id="nav3">
		<section>
			<p>  untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library unt<br>uk mempermudah kita membuat project.  untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk <br>mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project. untuk menggunakan fungsi redirect di codeigniter kita harus load help url terlebih dahulu.Redirect menggunakan Codeigniter itu cukup mudah karena codeigniter usdah menyapkan module atau library untuk mempermudah kita membuat project.</p>
		</section>
	</div>

</body>
</html>